### ISSUE TITLE
show all, show validated, show un-validated

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-org/vars-gridview#55]
Now that I've discovered the ability to hide validated (which is awesome), I would also like to have the ability to hide unvalidated too. So three views I would like and these could be a drop down selection:

1. show all
2. hide validated
3. hide unvalidated

**Comment by kevinsbarnard** [comment]
Related to #48, I want to add a slightly more involved UI to support filtering loaded results in the grid view, since I think there are other fields we may want to filter by as well (without doing a whole new query) going forward. In any case, I'll prioritize adding these options when I get to this.

**Comment by NancyJS** [comment]
Show only validated is the only one not currently on list, but you can sort by verifier, which puts all of the unverified together. Kevin will also add a tick box, so we'll have two options.
